package com.censocustody.android.ui.theme

import androidx.compose.ui.graphics.Color

val BackgroundWhite = Color(0xFFFFFFFF)
val BackgroundGrey = Color(0xFFF6F6F6)
val CensoTextBlue = Color(0xFF05B5FF)
val ButtonRed = Color(0xFFD8232A)
val TextRed = Color(0xFFD8232A)
val TextBlack = Color(0xFF1A1919)
val DarkGreyText = Color(0xFF666666)
val BorderGrey = Color(0xFFEDEDED)
val BackgroundDark = Color(0xFFEDEDED)
val BackgroundLight = Color(0xFFFFFFFF)
val CensoWhite = Color.White
val UnfocusedGrey = Color(0xFF373737)
val ApprovalGreen = Color(0xFF09ae75)
val DetailApprovalGreen = Color(0xFF9ec655)
val DetailApprovalGreenBackground = Color(0xFFE4EDD4)
val DetailDenyRed = Color(0xFFa34746)
val ErrorRed = Color(0xFFc8493e)
val ErrorBorderRed = Color(0xFFff0000)
val DetailDenyRedBackground = Color(0xFFEACDCD)
val GreyText = Color(0xFF8c8c8c)
val SnackbarBackground = Color(0xFF363636)
val DividerGrey = Color(0xFF3c3c3c)
val AllSetGreen = Color(0xFF92c83e)
val GreyOutline = Color(0XFF979797)
val VerifyWordsBorder = Color(0xFF8c8c8c)
val CancelButtonGrey = Color(0xFF32323d)
val DialogHeaderBackground = Color(0xFFF6F6F6)
val DialogMainBackground = Color(0xFFFFFFFF)
val TopAppBarText = Color(0xFF050422)
