name: Android CI

on:
  workflow_call:
    inputs:
      variant:
        required: true
        type: string
    secrets:
      googleServices:
        required: true
      firebaseToken:
        required: true
      keystore:
        required: true
      passphrase:
        required: true
      keyPassword:
        required: true
      createFirebaseBuild:
        required: true
      alias:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup config.properties
        run: |
          touch ./config.properties
          echo SIGN_BUILD=true >> ./config.properties
          echo RELEASE_STORE_PASSWORD="${{ secrets.keyPassword }}" >> ./config.properties
          echo RELEASE_KEY_ALIAS="${{ secrets.alias }}" >> ./config.properties

          echo "${{ secrets.keystore }}" > keystore.jks.asc
          gpg -d --passphrase "${{ secrets.passphrase }}" --batch keystore.jks.asc > app/keystore.jks

      - name: Add google services json
        env:
          DATA: ${{ secrets.googleServices }}
        run: |
          cat /home/runner/work/censo-security-android/censo-security-android/app/google-services.json | base64
          echo $DATA > /home/runner/work/censo-security-android/censo-security-android/app/google-services.json

      - name: Run lint
        run: "./gradlew lint${{ inputs.variant }}"

      - name: Run unit tests
        run: "./gradlew test${{ inputs.variant }}UnitTest"

      - name: Stop previous gradle
        run: ./gradlew --stop

      - if: createFirebaseBuild
        name: Upload build to firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.firebaseToken }}
        run: "./gradlew assemble${{ inputs.variant }} appDistributionUpload${{ inputs.variant }}"